In [16]:
import pandas as pd
import numpy as np
import pickle


In [17]:
# list the files in the current directory using python
import os
import sys
# get the current directory
current_dir = os.getcwd()
# print the files in the current directory
files =  os.listdir(current_dir)
# remove files that do not end with pkl
files = [file for file in files if file.endswith(".pkl")]
# print the files
print(files)

['agent_state_219_98_LightGlue.pkl', 'agent_state_220_100_LightGlue.pkl', 'agent_state_222_103_LightGlue.pkl', 'agent_state_218_91_LightGlue.pkl', 'agent_state_221_102_LightGlue.pkl', 'agent_state_191_89_LightGlue.pkl', 'agent_state_205_103_LightGlue.pkl', 'agent_state_207_105_LightGlue.pkl', 'agent_state_194_91_LightGlue.pkl', 'agent_state_217_90_LightGlue.pkl', 'agent_state_202_100_LightGlue.pkl', 'agent_state_193_90_LightGlue.pkl', 'agent_state_223_105_LightGlue.pkl', 'agent_state_204_102_LightGlue.pkl', 'agent_state_200_98_LightGlue.pkl', 'agent_state_216_89_LightGlue.pkl']


In [18]:
results_dict = {}
results_dict['filenames'] = sorted(files)
results_dict

{'filenames': ['agent_state_191_89_LightGlue.pkl',
  'agent_state_193_90_LightGlue.pkl',
  'agent_state_194_91_LightGlue.pkl',
  'agent_state_200_98_LightGlue.pkl',
  'agent_state_202_100_LightGlue.pkl',
  'agent_state_204_102_LightGlue.pkl',
  'agent_state_205_103_LightGlue.pkl',
  'agent_state_207_105_LightGlue.pkl',
  'agent_state_216_89_LightGlue.pkl',
  'agent_state_217_90_LightGlue.pkl',
  'agent_state_218_91_LightGlue.pkl',
  'agent_state_219_98_LightGlue.pkl',
  'agent_state_220_100_LightGlue.pkl',
  'agent_state_221_102_LightGlue.pkl',
  'agent_state_222_103_LightGlue.pkl',
  'agent_state_223_105_LightGlue.pkl']}

In [19]:
results_dict['num_exp']=[1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8]
results_dict

{'filenames': ['agent_state_191_89_LightGlue.pkl',
  'agent_state_193_90_LightGlue.pkl',
  'agent_state_194_91_LightGlue.pkl',
  'agent_state_200_98_LightGlue.pkl',
  'agent_state_202_100_LightGlue.pkl',
  'agent_state_204_102_LightGlue.pkl',
  'agent_state_205_103_LightGlue.pkl',
  'agent_state_207_105_LightGlue.pkl',
  'agent_state_216_89_LightGlue.pkl',
  'agent_state_217_90_LightGlue.pkl',
  'agent_state_218_91_LightGlue.pkl',
  'agent_state_219_98_LightGlue.pkl',
  'agent_state_220_100_LightGlue.pkl',
  'agent_state_221_102_LightGlue.pkl',
  'agent_state_222_103_LightGlue.pkl',
  'agent_state_223_105_LightGlue.pkl'],
 'num_exp': [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]}

In [20]:
results_df = pd.DataFrame(results_dict)
results_df

filenames  num_exp
0    agent_state_191_89_LightGlue.pkl        1
1    agent_state_193_90_LightGlue.pkl        2
2    agent_state_194_91_LightGlue.pkl        3
3    agent_state_200_98_LightGlue.pkl        4
4   agent_state_202_100_LightGlue.pkl        5
5   agent_state_204_102_LightGlue.pkl        6
6   agent_state_205_103_LightGlue.pkl        7
7   agent_state_207_105_LightGlue.pkl        8
8    agent_state_216_89_LightGlue.pkl        1
9    agent_state_217_90_LightGlue.pkl        2
10   agent_state_218_91_LightGlue.pkl        3
11   agent_state_219_98_LightGlue.pkl        4
12  agent_state_220_100_LightGlue.pkl        5
13  agent_state_221_102_LightGlue.pkl        6
14  agent_state_222_103_LightGlue.pkl        7
15  agent_state_223_105_LightGlue.pkl        8

In [21]:
results_df['environment'] = ['c', 'c', 'c', 'h', 'h', 'h', 'h', 'h', 'c', 'c', 'c', 'h', 'h', 'h', 'h', 'h']
results_df

filenames  num_exp environment
0    agent_state_191_89_LightGlue.pkl        1           c
1    agent_state_193_90_LightGlue.pkl        2           c
2    agent_state_194_91_LightGlue.pkl        3           c
3    agent_state_200_98_LightGlue.pkl        4           h
4   agent_state_202_100_LightGlue.pkl        5           h
5   agent_state_204_102_LightGlue.pkl        6           h
6   agent_state_205_103_LightGlue.pkl        7           h
7   agent_state_207_105_LightGlue.pkl        8           h
8    agent_state_216_89_LightGlue.pkl        1           c
9    agent_state_217_90_LightGlue.pkl        2           c
10   agent_state_218_91_LightGlue.pkl        3           c
11   agent_state_219_98_LightGlue.pkl        4           h
12  agent_state_220_100_LightGlue.pkl        5           h
13  agent_state_221_102_LightGlue.pkl        6           h
14  agent_state_222_103_LightGlue.pkl        7           h
15  agent_state_223_105_LightGlue.pkl        8           h

In [22]:
# open the first pickle file as a dataframe
import pandas as pd
import pickle
with open(files[0], 'rb') as f:
    data = pickle.load(f)
data

[AgentState(position=array([-5.4343696 ,  0.072447  ,  0.48555583], dtype=float32), rotation=quaternion(-0.748955428600311, 0, -0.662620484828949, 0), sensor_states={'rgb': SixDOFPose(position=array([-5.4343696 ,  1.3224471 ,  0.48555583], dtype=float32), rotation=quaternion(-0.748955428600311, 0, -0.662620484828949, 0)), 'depth': SixDOFPose(position=array([-5.4343696 ,  1.3224471 ,  0.48555583], dtype=float32), rotation=quaternion(-0.748955428600311, 0, -0.662620484828949, 0))}),
 AgentState(position=array([-5.533624,  0.072447,  0.473369], dtype=float32), rotation=quaternion(-0.748955428600311, 0, -0.662620484828949, 0), sensor_states={'rgb': SixDOFPose(position=array([-5.533624 ,  1.3224471,  0.473369 ], dtype=float32), rotation=quaternion(-0.748955428600311, 0, -0.662620484828949, 0)), 'depth': SixDOFPose(position=array([-5.533624 ,  1.3224471,  0.473369 ], dtype=float32), rotation=quaternion(-0.748955428600311, 0, -0.662620484828949, 0))}),
 AgentState(position=array([-5.632879  ,

In [23]:
import numpy as np

def compute_trajectory_length(data):
    if len(data) < 2:
        return 0.0
    positions = [agent_state.position for agent_state in data]
    total_length = 0.0
    for i in range(len(positions) - 1):
        current_pos = positions[i]
        next_pos = positions[i + 1]
        delta = next_pos - current_pos
        distance = np.linalg.norm(delta)
        total_length += distance
    return total_length

In [24]:
traj_len = []
file_len = []
for file in files:
    with open(file, 'rb') as f:
        data = pickle.load(f)
    file_len.append(len(data))
    traj = compute_trajectory_length(data)
    traj_len.append(traj)


In [25]:
results_df['traj_len'] = traj_len
results_df['num_steps'] = file_len
results_df

filenames  num_exp environment   traj_len  \
0    agent_state_191_89_LightGlue.pkl        1           c   4.618981   
1    agent_state_193_90_LightGlue.pkl        2           c   7.899990   
2    agent_state_194_91_LightGlue.pkl        3           c   5.800001   
3    agent_state_200_98_LightGlue.pkl        4           h   3.503600   
4   agent_state_202_100_LightGlue.pkl        5           h   6.900005   
5   agent_state_204_102_LightGlue.pkl        6           h   6.614958   
6   agent_state_205_103_LightGlue.pkl        7           h   5.800001   
7   agent_state_207_105_LightGlue.pkl        8           h  11.900366   
8    agent_state_216_89_LightGlue.pkl        1           c   4.304623   
9    agent_state_217_90_LightGlue.pkl        2           c  26.449447   
10   agent_state_218_91_LightGlue.pkl        3           c   7.800003   
11   agent_state_219_98_LightGlue.pkl        4           h  26.649859   
12  agent_state_220_100_LightGlue.pkl        5           h  11.999999   
13  agent_state_221_102_LightGlue.pkl        6           h   6.888394   
14  agent_state_222_103_LightGlue.pkl        7           h   4.678687   
15  agent_state_223_105_LightGlue.pkl        8           h   6.514666   

    num_steps  
0         129  
1         167  
2         173  
3         121  
4         180  
5         188  
6         172  
7         299  
8         154  
9         652  
10        214  
11        724  
12        303  
13        230  
14        184  
15        184

In [26]:
ipc_df = results_df.iloc[0:8]
ipc_df

filenames  num_exp environment   traj_len  \
0   agent_state_191_89_LightGlue.pkl        1           c   4.618981   
1   agent_state_193_90_LightGlue.pkl        2           c   7.899990   
2   agent_state_194_91_LightGlue.pkl        3           c   5.800001   
3   agent_state_200_98_LightGlue.pkl        4           h   3.503600   
4  agent_state_202_100_LightGlue.pkl        5           h   6.900005   
5  agent_state_204_102_LightGlue.pkl        6           h   6.614958   
6  agent_state_205_103_LightGlue.pkl        7           h   5.800001   
7  agent_state_207_105_LightGlue.pkl        8           h  11.900366   

   num_steps  
0        129  
1        167  
2        173  
3        121  
4        180  
5        188  
6        172  
7        299

In [27]:
ibvs_df = results_df.iloc[8:16]
ibvs_df

filenames  num_exp environment   traj_len  \
8    agent_state_216_89_LightGlue.pkl        1           c   4.304623   
9    agent_state_217_90_LightGlue.pkl        2           c  26.449447   
10   agent_state_218_91_LightGlue.pkl        3           c   7.800003   
11   agent_state_219_98_LightGlue.pkl        4           h  26.649859   
12  agent_state_220_100_LightGlue.pkl        5           h  11.999999   
13  agent_state_221_102_LightGlue.pkl        6           h   6.888394   
14  agent_state_222_103_LightGlue.pkl        7           h   4.678687   
15  agent_state_223_105_LightGlue.pkl        8           h   6.514666   

    num_steps  
8         154  
9         652  
10        214  
11        724  
12        303  
13        230  
14        184  
15        184

In [28]:
vs_dict = {}
vs_df = pd.DataFrame(vs_dict)
vs_df['ipc_results'] = list(zip(ipc_df['traj_len'], ipc_df['num_steps']))
vs_df['ibvs_results'] = list(zip(ibvs_df['traj_len'], ibvs_df['num_steps']))
vs_df

ipc_results               ibvs_results
0  (4.6189805418252945, 129)   (4.304622866213322, 154)
1   (7.899989552795887, 167)   (26.44944690167904, 652)
2   (5.800001159310341, 173)  (7.8000031262636185, 214)
3   (3.503600090742111, 121)   (26.64985940605402, 724)
4   (6.900004543364048, 180)  (11.999999187886715, 303)
5   (6.614958189427853, 188)   (6.888393543660641, 230)
6   (5.800001077353954, 172)    (4.67868678830564, 184)
7  (11.900366343557835, 299)  (6.5146655812859535, 184)

In [ ]:
goal_locations =[]
goal_ids = [89, 90, 91, 98, 100, 102, 103, 105]
goal_root = '/home/rodriguez/Documents/GitHub/habitat/habitat-lab/selected_frames/path_'

for ids in goal_ids:
    goal_filename = goal_root + str(ids) + '/selected_poses_' + str(ids) + '.pkl'
    with open(goal_filename, 'rb') as f:
        key_locations = pickle.load(f)
    goal_locations.append(key_locations[-2].position)

In [45]:
goal_locations

[array([ 1.2329898 ,  0.18494621, 19.75083   ], dtype=float32),
 array([-5.5307145 ,  0.07762152,  8.396897  ], dtype=float32),
 array([ 2.36144   ,  0.17307578, 16.304327  ], dtype=float32),
 array([-9.195042  ,  0.072447  , -0.34298816], dtype=float32),
 array([-2.8716679,  0.072447 , -1.5049287], dtype=float32),
 array([-4.7052526,  0.072447 , -2.3648424], dtype=float32),
 array([ 1.8839558,  0.072447 , -1.0086691], dtype=float32),
 array([-9.119458 ,  0.072447 ,  0.1528655], dtype=float32)]

In [47]:
final_ipc_locations = []
for files in ipc_df['filenames']:
    with open(files, 'rb') as f:
        data = pickle.load(f)
    final_ipc_locations.append(data[-1].position)
final_ipc_locations

[array([ 2.1837273,  0.1449068, 19.79688  ], dtype=float32),
 array([-5.59591   ,  0.07747218,  8.415543  ], dtype=float32),
 array([ 2.1187224 ,  0.20991862, 15.444453  ], dtype=float32),
 array([-9.142073 ,  0.072447 , -0.9900901], dtype=float32),
 array([-2.094802 ,  0.072447 , -1.6905824], dtype=float32),
 array([-4.70113 ,  0.072447, -2.402492], dtype=float32),
 array([ 1.8960137,  0.072447 , -1.0203854], dtype=float32),
 array([-9.115802  ,  0.072447  ,  0.18155405], dtype=float32)]

In [48]:
final_ibvs_locations = []
for files in ibvs_df['filenames']:
    with open(files, 'rb') as f:
        data = pickle.load(f)
    final_ibvs_locations.append(data[-1].position)
final_ibvs_locations

[array([ 2.1965568,  0.1440148, 19.76631  ], dtype=float32),
 array([-5.6369123 ,  0.07554396,  8.38936   ], dtype=float32),
 array([ 2.2647865 ,  0.18764284, 16.102959  ], dtype=float32),
 array([-9.188775 ,  0.072447 , -0.9541875], dtype=float32),
 array([-2.2193935,  0.072447 , -1.6475316], dtype=float32),
 array([-4.8030605,  0.072447 , -2.4669375], dtype=float32),
 array([ 1.8989062,  0.072447 , -0.9949347], dtype=float32),
 array([-9.09973   ,  0.072447  ,  0.16543746], dtype=float32)]

In [53]:
dist_goal_ipc_list = [np.linalg.norm(gl-fl) for gl, fl in zip(goal_locations, final_ipc_locations)]
dist_goal_ibvs_list = [np.linalg.norm(gl-fl) for gl, fl in zip(goal_locations, final_ibvs_locations)]
dist_goal_tuple = list(zip(dist_goal_ipc_list, dist_goal_ibvs_list))
dist_goal_tuple

[(0.9526938, 0.9645602),
 (0.067809515, 0.10648522),
 (0.8942327, 0.22383766),
 (0.6492662, 0.6112315),
 (0.7987415, 0.6676806),
 (0.037874684, 0.14138529),
 (0.016812596, 0.02030147),
 (0.028920617, 0.023393894)]

In [54]:
vs_df['dist_goal(ipc,ibvs)'] = dist_goal_tuple
vs_df

ipc_results               ibvs_results  \
0  (4.6189805418252945, 129)   (4.304622866213322, 154)   
1   (7.899989552795887, 167)   (26.44944690167904, 652)   
2   (5.800001159310341, 173)  (7.8000031262636185, 214)   
3   (3.503600090742111, 121)   (26.64985940605402, 724)   
4   (6.900004543364048, 180)  (11.999999187886715, 303)   
5   (6.614958189427853, 188)   (6.888393543660641, 230)   
6   (5.800001077353954, 172)    (4.67868678830564, 184)   
7  (11.900366343557835, 299)  (6.5146655812859535, 184)   

          dist_goal(ipc,ibvs)  
0      (0.9526938, 0.9645602)  
1   (0.067809515, 0.10648522)  
2     (0.8942327, 0.22383766)  
3      (0.6492662, 0.6112315)  
4      (0.7987415, 0.6676806)  
5   (0.037874684, 0.14138529)  
6   (0.016812596, 0.02030147)  
7  (0.028920617, 0.023393894)